openapi: 3.0.0
info:
  title: STD23042 - TD1
  version: 1.0.0
servers:
  - url: https://localhost.STD23042.com
paths:
  /customers:
    get:
      summary: Get list of customers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
